exception File_not_found of string

type t
(** AF : ['a t] is the representation type of a dictionary that contains all
    words in a given text file. *)

(** RF : Duplicate elements are not allowed in the dictionary. *)

val empty : t
(** [empty] is the representation of an empty dictionary.*)

val create_lines_list : string -> string list
(** [create_lines_list file_name] is a function that takes in the text file to
    be spellchecked [file_name] and returns a string list where each element is
    a seperate line in [file_name]. Duplicate elements are allowed in the
    returned string list. *)

val create_dict : string -> t -> string list
(** [create_dict file_name dict] is a function that inserts all words added to
    the string list generated by [create_lines_list] to the dictionary [dict],
    while removing all duplicates.*)

val fold : string list -> string
(** [fold lst] is a function that returns the string representation of the
    dictionary [lst]. *)
